Prepared App for different localisations
hartlco/Icro pull request #8
Opened 2018-08-26 23:01 UTC by sauberfred

Switched from hardcoded strings to NSLocalizedStrings

2018-08-28 17:30 UTC, hartlco requested changes
This is a great PR, thank you!
I noticed this PR introduces 4 new warning because of SwiftLint. Those should be fixed before merging. For the future I plan to integrate the SwiftLint checks into the CI pipeline.

I also added one comment about the outlets in the Settings.

Let me know if you are interested in fixing the issues, otherwise I would merge it and fix it in hindsight!

2018-08-28 17:30 UTC, hartlco commented on Icro/ViewController/SettingsViewController.swift
> +    @IBOutlet weak var blogSetupSwitchLabel: UILabel!
I think all the newly introduced outlets should be `private` properties as well.

2018-08-28 20:17 UTC, sauberfred commented
You are welcome!
I fixed the SwiftLint warnings and made the new outlets private.

2018-08-28 20:22 UTC, sauberfred commented on Icro/ViewController/InsertLinkViewController.swift
> +    @IBOutlet private weak var linkTextField: UITextField!
I also made linkTextField private, but can revert if you do not want it to be private.

2018-08-29 18:01 UTC, hartlco commented
Great, merging now!

2018-08-29 18:01 UTC, hartlco approved these changes

2018-08-29 18:01 UTC, merged